rules:
    indentation:
        - 2
        -
            size: 4

    single-line-per-selector:
        - 0

    variable-name-format:
        - 2
        -
            convention: "snakecase"

    class-name-format:
        - 2
        -
            convention: "snakecase"

    selector-format:
        - 2
        -
            convention: "snakecase"

    hex-notation:
        - 2
        -
            style: "uppercase"

    hex-length:
        - 2
        -
            style: "long"

    force-pseudo-nesting:
        - 0

    force-element-nesting:
        - 0

    no-qualifying-elements:
        - 0

