# info on commissioned art..
ART_DATA = [
    {
        "type": "pfp-art",
        "link": "/gallery/commart/tree.jpg",
        "alt": "tree",
        "title": "tree",
        "subject": "a tree",
        "artist": {
            "link": "https://drew.life",
            "name": "drew/python",
        },
        "date": "forget",
        "category": "demo",
        "category-label": "demo",
    },
    {
        "type": "pfp-art",
        "link": "/gallery/commart/aspeneyes_profile.png",
        "alt": "Aspen Eyes fursona profile",
        "title": "Aspen Eyes fursona profile",
        "subject": "Alix (fursona)",
        "artist": {
            "link": "https://twitter.com/aspen_eyes",
            "name": "Aspen Eyes",
        },
        "date": "2020-05-07",
        "category": "fursona",
        "category-label": "fursona",
    },
    {
        "type": "fullbody-art",
        "link": "/gallery/commart/fullbody1.jpg",
        "alt": "Mirtilo fursona fullbody",
        "title": "Mirtilo fursona fullbody",
        "subject": "Alix (fursona)",
        "artist": {
            "link": "https://www.furaffinity.net/user/mirtilo/",
            "name": "Mirtilo",
        },
        "date": "tbd-TBD-tbd",
        "category": "fursona",
        "category-label": "fursona",
    },
    {
        "type": "pfp-art",
        "link": "/gallery/commart/pitanga_profile.jpg",
        "alt": "Pitanga fursona profile",
        "title": "Pitanga fursona profile",
        "subject": "Alix (fursona)",
        "artist": {
            "link": "https://twitter.com/pitangabag",
            "name": "Pitanga",
        },
        "date": "2021-01-09",
        "category": "fursona",
        "category-label": "fursona",
    },
    {
        "type": "fullbody-art",
        "link": "/gallery/commart/fullbody2.jpg",
        "alt": "Nagunkgunk Anita-5 fullbody",
        "title": "Nagunkgunk Anita-5 fullbody",
        "subject": "Anita-5 (♀ Exo Warlock)",
        "artist": {
            "link": "https://twitter.com/nagunkgunk",
            "name": "nagunkgunk",
        },
        "date": "tbd-TBD-tbd",
        "category": "destiny2",
        "category-label": "destiny 2",
    },
]
