# info on commissioned art..
ART_DATA = [
    {
        "type": "pfp-art",
        "link": "/gallery/commart/tree.jpg",
        "alt": "tree",
        "title": "tree",
        "subject": "a tree",
        "artist": {
            "link": "https://drew.life",
            "name": "drew/python",
        },
        "date": "forget",
        "category": "demo",
        "category-label": "demo",
    },
    {
        "type": "pfp-art",
        "link": "/gallery/commart/aspeneyes_alix_profile.png",
        "alt": "Aspen Eyes fursona profile",
        "title": "Aspen Eyes fursona profile",
        "subject": "Alix (fursona)",
        "artist": {
            "link": "https://twitter.com/aspen_eyes",
            "name": "Aspen Eyes",
        },
        "date": "2020-05-07",
        "category": "fursona",
        "category-label": "fursona",
    },
    {
        "type": "fullbody-art",
        "link": "/gallery/commart/mirtilo_alix_fullbody.png",
        "alt": "Mirtilo fursona fullbody",
        "title": "Mirtilo fursona fullbody",
        "subject": "Alix (fursona)",
        "artist": {
            "link": "https://twitter.com/mirtiloart",
            "name": "Mirtilo",
        },
        "date": "2021-02-18",
        "category": "fursona",
        "category-label": "fursona",
    },
    {
        "type": "pfp-art",
        "link": "/gallery/commart/pitanga_alix_profile.jpg",
        "alt": "Pitanga fursona profile",
        "title": "Pitanga fursona profile",
        "subject": "Alix (fursona)",
        "artist": {
            "link": "https://twitter.com/pitangabag",
            "name": "Pitanga",
        },
        "date": "2021-01-09",
        "category": "fursona",
        "category-label": "fursona",
    },
    {
        "type": "fullbody-art",
        "link": "/gallery/commart/nagunkgunk_anita-5_fullbody.png",
        "alt": "Nagunkgunk Anita-5 fullbody",
        "title": "Nagunkgunk Anita-5 fullbody",
        "subject": "Anita-5 (♀️ exo warlock)",
        "artist": {
            "link": "https://twitter.com/nagunkgunk",
            "name": "Nagunkgunk",
        },
        "date": "2021-01-29",
        "category": "destiny2",
        "category-label": "destiny 2",
    },
    {
        "type": "fullbody-art",
        "link": "/gallery/commart/self-made self-ref 1.0 June 2021.png",
        "alt": "Alix Novosi Reference Sheet",
        "title": "Alix Novosi Reference Sheet",
        "subject": "Alix (fursona)",
        "artist": {
            "link": "https://twitter.com/alixnovosi",
            "name": "Alix Novosi",
        },
        "date": "2021-06-17",
        "category": "fursona",
        "category-label": "fursona",
    },
]
